//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Rented
    {
        public string c_name { get; set; }
        public int id { get; set; }
        public string c_choice { get; set; }
        public Nullable<System.DateTime> i_date { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public Nullable<double> t_amount { get; set; }
    }
}
